@startuml

package app {
    class Main
    class StateHandler {
        +process()
        +setState(AbstractState&)
    }

    interface AbstractState {
        {abstract}+AbstractState(StateHandler&)
        {abstract} +enter()
        {abstract} +process()
        {abstract} +leave()
    }

    class Parameter {

    }

    package States {
        class SleepState
        class UpdateState
        class InitState
        class ErrorState
        class LowBatteryState

        UpdateState -u-|> AbstractState
        SleepState -u-|> AbstractState
        InitState -u-|> AbstractState
        ErrorState -u-|> AbstractState
        LowBatteryState -u-|> AbstractState
    }

    Main -> StateHandler
    StateHandler --> AbstractState
}

package Service {
    class FileIO {
        +enable(bool)
    }
    class FatFS
    class ServiceInit {
      
    }
    class Display {
        +init()
        +reset()
        +beginPaint()
        +endPaint()
        +sendBlock()
    }
    class SDCard {
        +disk_initialize()
        +disk_status()
        +disk_read()
    }

    class Debug
    
    class Led {

    }

    class Power {
        +enable(Device)
        +disable(Device)
        +halt()
        +idle()
    }

    class Settings {

    }

}

package Hal {

    class Spi 
    class Uart {
        init(Baud,bits, parity, stopBit)

    }
    
    class HalInit
    class Cpu {
        +enable(Device, bool)
        +sleep()
    }
    class Gpio {
        +init()
        +setPinXXX()
        +clrPinXXX()
        +getPinXXX()
    }

    class TickTimer {
        +init()
        +enable()
        +disable()
        +getTickCount()
    }
    
    class WakeUpTimer {
        +init()
        +enable()
        +disable()
    }

    class Adc {
        +init()
        +disable()
        +enable()
        +readChannel()
    }

    class EEprom {
        +read()
    }

}

InitState --> ServiceInit
InitState --> Led
ServiceInit --> HalInit
UpdateState --> FileIO
UpdateState --> Display
SleepState --> Power
ErrorState --> Power
UpdateState --> Power
Parameter --> Settings

FileIO ->FatFS
FatFS --> SDCard
FileIO --> SDCard

Debug --> Uart
Debug --> Gpio
SDCard --> Spi
Display --> Spi
Display --> Gpio
Power --> Cpu
Power --> WakeUpTimer
Power --> Gpio
Power ---> Adc
FatFS --> TickTimer
Settings --> EEprom
Led --> Gpio

@enduml