@startuml StateMachine

[*] -r-> Init : Power On
Init -->  Update

Update -> Sleep : Update done
Sleep -l> Update : Wakeup time passed

Update -d-> Error : Error occured
Sleep -d-> Error : Error occured

Update --> LowBatteryHalt : Low voltage level reached
Error -d-> [*] : halt
LowBatteryHalt -d->[*] : halt
Init: /enter initSystem()
Init: /process setState(Update)

Error: /enter DisplayErrImage()
Error: /process halt()

Update: /process checkVoltage()
Update: /process displayNextImage()

Sleep: /enter suspendDevices()
Sleep: /process sleep( Wakeup time period)
Sleep: /leave resumeDevices()

LowBatteryHalt: /entry DisplayLowBatImage()
LowBatteryHalt: /process halt()

@enduml