@startuml Context

node PC as PC

interface USB as UsbChrger

node EInkFrame {
    node "E-Ink Display" as DISPLAY {

    }

    node Charger as Chrgr {

    }

    node MainBoard as BOARD {
        node AVR328P  as UC  << uc >>{
            file Software
        }

        node LED as LED

        node UART as RS232

        node DispFET as DispFet
        node SDFET as SDFet

        interface SPI as SPI

        Interface ISP as ISP
    }

    node SD-Card as SDCARD {
        file Images
    }

    node Battery as BAT {

    }

    UsbChrger ->Chrgr : Power
    Chrgr -r-> BAT : Power
    BAT -d-> BOARD : Power
    UC -- SPI
    SPI -- SDCARD : SPI
    SPI -- DISPLAY : SPI
    UC -- DispFet
    UC -- SDFet
    UC -up-> RS232 : Debug
    UC -up-> LED
    DispFet -> DISPLAY : Power
    SDFet -> SDCARD : Power
    ISP -- UC
    PC -d- ISP
}
@enduml